services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: plottr_postgres
    environment:
      POSTGRES_USER: plottr
      POSTGRES_PASSWORD: plottrpass
      POSTGRES_DB: plottr_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plottr"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - plottr_postgres_data:/var/lib/postgresql/data

volumes:
  plottr_postgres_data:
