name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=12

    env:
      NODE_ENV: test
      DATABASE_URL_TEST: postgres://postgres:postgres@localhost:5432/plottr_test
      PGPASSWORD: postgres
      PGUSER: postgres
      PGHOST: localhost
      PGPORT: "5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create test DB and enable extensions
        run: |
          psql -v ON_ERROR_STOP=1 -h $PGHOST -U $PGUSER -d postgres -c "CREATE DATABASE plottr_test;"
          psql -v ON_ERROR_STOP=1 -h $PGHOST -U $PGUSER -d plottr_test -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          psql -v ON_ERROR_STOP=1 -h $PGHOST -U $PGUSER -d plottr_test -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

      - name: Run migration tests
        run: npm run test:migrations

      - name: Run integration tests
        run: npm run test:integration
